project_id = "kazjpebvshepisrbahqu"

[functions.gerar-mensalidades-mensais]
verify_jwt = false

[functions.processar-extrato-bancario]
verify_jwt = true

[functions.manage-admin-users]
verify_jwt = true
